apiVersion: v1
kind: Service
metadata:
  name: App
  namespace: default
  labels:
    run: App
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - name: port
    port: 7000
    protocol: TCP

---
apiVersion: v1
kind: Endpoints
metadata:
  name: App 
  namespace: default
  labels:
    run: App
subsets:
- addresses:
  - ip: 10.8.0.19
    nodeName: App-01
  - ip: 10.8.2.17
    nodeName: App-02
  ports:
  - name: port
    port: 7000
    protocol: TCP