apiVersion: v1
kind: ReplicationController    #类型为副本控制器RC
metadata:
  name: mysql                  #RC的名称，全局唯一
spec:
   replicas: 1                 #POD副本期待数量
   selector:
     app: mysql                #符合目标的Pod拥有此标签
   template:                   #根据此模板创建Pod的副本
     metadata:
       labels:
         app: mysql            #Pod副本拥有的标签，对应RC的Selector
     spec:
       containers:             #Pod内容器的定义部分
       - name: mysql           #容器的名称
         image: mysql.io/mysql:latest    #容器对应的Docker Image
         ports:
         - containerPort: 3306           #容器应用监听的端口号
         env:                            #注入容器内的环境变量
         - name: MYSQL_ROOT_PASSWORD
           value: "123456"
         - name: MYSQL_SERVER_ID
           value: "1"