apiVersion: v1
kind: Service
metadata:
  name: mysql
spec:
  type: NodePort
  ports:
   - port: 3306
     nodePort: 30014
  selector:
    app: mysql


---
#mysql数据持久化 （基于nfs）
apiVersion: v1                     #版本号
kind: ReplicationController        #使用rc资源类型
metadata:
  name: mymysql                    #pod的名称
spec:
  replicas: 1                      #启动副本的数量
  selector:
   app: mymysql
  template:
   metadata:
     labels:
       app: mymysql
   spec:
     containers:
     - name: mymysql            #自定义镜像名称
       image: mysql:5.6.20      #镜像信息
       ports:
       - containerPort: 3306    #镜像的端口号
       env:                     #定义环境变量
       - name: MYSQL_ROOT_PASSWORD    #定义mysql的root密码
         value: "123456"              #root密码
       volumeMounts:                  
       - mountPath: /var/lib/mysql    #容器的挂载路径
         readOnly: false              #可读可写
         name: mysql1-data            #自定义名称
     volumes:
       - name: mysql1-data            #宿主机的自定义名称
         nfs:                         #使用宿主机的nfs方式挂载
           server: 192.168.1.89       #nfs服务器地址
           path: "/app/mysql1_data"   #nfs共享的路径

---
#mysql配置文件持久化
apiVersion: v1
kind: ReplicationController
metadata:
  name: mymysql
spec:
  replicas: 1
  selector:
   app: mymysql
  template:
   metadata:
     labels:
       app: mymysql
   spec:
     containers:
     - name: mymysql
       image: mysql:5.6.20
       ports:
       - containerPort: 3309         #修改了mysql默认端口微3309
       env:
       - name: MYSQL_ROOT_PASSWORD
         value: "123456"
       volumeMounts:
        - mountPath: /etc/my.cnf
          name: conf
     volumes:
      - hostPath:
         path: /data/my.cnf
        name: conf