apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx4
spec:
   replicas: 1
   selector:
     app: nginx4
   template:
     metadata:
       labels:
         app: nginx4
     spec:
       containers:
       - name: nginx4
         image: 10.0.0.10:5000/nginx:v2
         ports:
         - containerPort: 80
         volumeMounts:
          - mountPath: /usr/local/nginx/html     #容器的站点目录
            name: web
       volumes:
        - hostPath:
           path: /root/test                      #本地（宿主机）目录
          name: web

--- 

apiVersion: v1
kind: ReplicationController
metadata:
  name: nginx2
spec:
   replicas: 1
   selector:
     app: nginx2
   template:
     metadata:
       labels:
         app: nginx2
     spec:
       containers:
       - name: nginx2
         image: nginx
         ports:
         - containerPort: 80
         volumeMounts:
         - mountPath: /usr/share/nginx/html
           readOnly: false
           name: nginx-data
       volumes:
       - name: nginx-data
         nfs:
           server: 192.168.1.89
           path: "/app/www_data"