apiVersion: v1
kind: ReplicationController
metadata:
  name: myweb
spec:
  replicas: 1
  selector:
   app: myweb
  template:
   metadata:
     labels:
       app: myweb
   spec:
     containers:
     - name: myweb
       image: docker.io/kubeguide/tomcat-app:v1
       ports:
       - containerPort: 8080

---
# tomcat数据持久化yaml文件（挂载多个目录）
apiVersion: v1
kind: ReplicationController
metadata:
  name: mytomcat10
spec:
  replicas: 1
  selector:
   app: mytomcat10
  template:
   metadata:
     labels:
       app: mytomcat10
   spec:
     containers:
     - name: mytomcat10
       image: docker.io/kubeguide/tomcat-app:v1
       ports:
       - containerPort: 8080
       volumeMounts:
        - mountPath: /usr/local/tomcat/apache-tomcat-8.5.23/webapps      #容器的站点地址
          name: web
        - mountPath: /usr/local/tomcat/apache-tomcat-8.5.23/conf         #容器的站点地址
          name: conf
     volumes:
      - hostPath:
         path: /data/webapps                  #宿主机的站点目录地址
        name: web
      - hostPath:
         path: /data/conf                     #宿主机的配置文件目录地址
        name: conf

---
#tomcat数据持久化（基于nfs）
apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat
spec:
   replicas: 1
   selector:
     app: tomcat
   template:
     metadata:
       labels:
         app: tomcat
     spec:
       containers:
       - name: tomcat
         image: tomcat:8
         ports:
         - containerPort: 8080
         volumeMounts:
         - mountPath: /usr/local/tomcat/webapps
           readOnly: false
           name: nginx-data
       volumes:
       - name: nginx-data
         nfs:
           server: 192.168.1.89             #nfs服务器地址
           path: "/app/www_data"            #nfs服务器共享的目录