---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
  - image: busybox
    name: test-emptydir
    command: [ "sleep", "3600" ]
    volumeMounts:
    - mountPath: /data
      name: data-volume #必须有名称
  volumes:
  - name: data-volume  #跟上面的名称对应
    emptyDir: {} #宿主机挂载点


