services:
  nginx:
    restart: always
    image: nginx
    container_name: nginx
    ports:
      - 8081:80
      - 443:443
      - 8084:8084
    volumes:
      - ./conf/nginx.conf:/etc/nginx/nginx.conf
      - ./conf.d:/etc/nginx/conf.d
      - ./www:/usr/share/nginx/html
      #- ./log:/var/log/nginx   #一定不要把nginx docker日志挂载到外部，否则fluentd无法正常工作
    privileged: true
    environment:
      - TZ=Asia/Shanghai
    logging:
        driver: "fluentd"    #日志驱动换成fluentd，默认为json-file
        options:
          fluentd-address: xx.xx.xx.xx:24224  #对应fluentd服务地址
          fluentd-async-connect: 'true'
          tag: nginx
