version: "3"
services:
  fluentd:
    image: fluent/fluentd
    container_name: fluentd
    volumes:
      - /data/fluentd/conf:/fluentd/etc
    privileged: true
    ports:
      - "24224:24224"
    environment:
      - TZ=Asia/Shanghai
    restart: always
    logging:
        driver: "json-file"
        options:
            max-size: 100m