---
jenkins:
  image: owen2016/jenkins:1.0
  hostname: 'gitlab.devopsing.site'
  privileged: true
  user: root
  restart: always
  container_name: jenkins
  ports:
    - "8080:8080"
    - "50000:50000"
  volumes:
    - /var/jenkins/:/var/jenkins_home
    - /var/run/docker.sock:/var/run/docker.sock
    - /usr/bin/docker:/usr/bin/docker
    - /etc/timezone:/etc/timezone
    - /etc/localtime:/etc/localtime
