apiVersion: v1
kind: ReplicationController # kind 指明此资源对象的类型
metadata:
  name: mysql # 元数据 - 此资源对象的名称，全局唯一
spec:
  replicas: 1 # Pod 副本期待的数量
  selector: 
    app: mysql # label 标签，选择有此 label 的 Pod
  template: # 定义创建 Pod 实例的模板 
    metadata: 
      labels:
        app: mysql # Pod 的 label，对应上面 rc 的 selector
        #需要特别注意的是：这里的labels必须匹配之前的spec.selector，否则RC每次创建了一个无法匹配Label的Pod，就会不停地尝试创建新的额Pod
    spec:
      containers: # 定义 Pod 中的容器
        - name: mysql # 容器名称
          image: mysql:5.6 # 使用的 docker image
          ports:
          - containerPort: 3306 # 容器暴露的端口号
          env:  # 注入到容器内的环境变量
          - name: MYSQL_ROOT_PASSWORD
            value: '123456'

