apiVersion: apps/v1
kind: Deployment
metadata:
  name: vuejs
spec:
  replicas: 1
  selector:
    matchLabels: 
     app: vuejs
  template:
    metadata:
      labels:
        app: vuejs
    spec:
      containers:
      - name: vuejs
        image: harbor.xxxx.com.cn/vuejs-docker:1.0.61_master_9438c18
        ports:
        - containerPort: 80
      imagePullSecrets:
       - name: augregistrykey

---
apiVersion: v1
kind: Service
metadata:
  name: vuejs-svc
spec:
  type: NodePort
  selector:
    app: vuejs
  ports:
    - protocol: TCP
      port: 8088
      targetPort: 80
      nodePort: 30081