library 'microServicesBuild'

pipeline {
    agent any
    tools {
        maven 'apache-maven-3.6.2'
    }
    stages {
        stage('Build') {
            steps {
                microServicesBuild('maven', 'build')
            }
        }
        stage('Deploy') {
            steps {
                microServicesBuild('maven', 'deploy')
            }
        }
    }
}