library 'microServicesBuild'

pipeline {
    agent any
    tools {
            maven 'apache-maven-3.6.0'
    }
    stages {
        stage('Build') {
            steps {
                echo 'Building...'
                microServicesBuild("maven", "build")
            }
        }
        stage('Test') {
            steps {
                echo 'Testing...'
                microServicesBuild("maven", "test")
            }
        }
        stage('Push docker image') {
            steps {
                echo 'Pushing docker image...'
                microServicesBuild("maven", "deploy")
            }
        }
//         stage('Deploy for production') {
//             steps {
//                 input message: 'Deploying the new production? (Click "Proceed" to continue)'
//                 ansiblePlaybook(
//                     playbook: 'deploy.yml',
//                     inventory: './inventory',
//                     // credentialsId: '', 已通过ssh-copy-id建立ssh互信credentialsid还没用起来
//                     colorized: true
//                     )
//             }
//         }
    }
    post {
            failure {
                script {
                    echo "The pipeline failed ..."

                    // mail to: 'XXXX@devops.com.cn', subject: 'The pipeline failed ...'
                }
            }

            success
            {
                echo "The pipeline success ..."
            }

            always
            {
                cleanWs() //清理工作空间
            }
    }
}