#chapter 1.3.3
apiVersion: v1
kind: Service
metadata:
  name: myweb
spec:
  type: NodePort #开启NodePort方式的外网访问模式
  ports:
  - port: 8080
    nodePort: 30001 # 开启NodePort方式的外网访问模式
  selector:
    app: myweb