- hosts: jenkins
  vars:
   #jenkins_hostname: jenkins.demo.com
   jenkins_http_port: 8080
   jenkins_version: "2.190.1"
   jenkins_pkg_url: "https://pkg.jenkins.io/debian-stable/binary/"

  roles:
    - role: java
      become: yes
    - role: jenkins
      become: yes

