#chapter_3.9.4
apiVersion: v1
kind: Pod
metadata:
  name: pod-flag
  labels:
    security: "S1"
    app: "nginx"
spec:
  containers:
  - name: nginx
    image: nginx
#创建名为pod-flag的Pod，带有标签security=S1和app=nginx