#chapter_3.12.2
---
apiVersion: monitoring.coreos.com/v1
kind: Prometheus
metadata:
  name: prometheus
  labels:
    app: prometheus
    prometheus: prometheus
spec:
  replicas: 1
  baseImage: prom/prometheus
  version: v2.8.0
  serviceMonitorSelector:
    matchLabels:
      service-monitor: function
  resources:
    requests:
      memory: 300Mi
---
apiVersion: v1
kind: Service
metadata:
  name: prometheus
  labels:
    app: prometheus
    prometheus: prometheus
spec:
  selector:
    prometheus: prometheus
  ports:
  - name: http
    port: 9090
#部署Prometheus服务