FROM node:8
LABEL maintainer="iyou999@126.com"
EXPOSE 7001

ENV LANG="C.UTF-8" \
    TZ="Asia/Shanghai"

WORKDIR /data/work/

#设置时区
RUN echo Asia/Chongqing > /etc/timezone \
  && ln -sfv /usr/share/zoneinfo/Asia/Chongqing /etc/localtime

RUN echo "deb http://mirrors.aliyun.com/debian/ jessie main non-free contrib \n\
deb http://mirrors.aliyun.com/debian/ jessie-proposed-updates main non-free contrib \n\
deb-src http://mirrors.aliyun.com/debian/ jessie main non-free contrib \n\
deb-src http://mirrors.aliyun.com/debian/ jessie-proposed-updates main non-free contrib" \
  > /etc/apt/sources.list \
  && apt-get update \
  && apt-get install -y libsasl2-dev libsasl2-modules-gssapi-heimdal \
  && rm -rf /var/lib/apt
  
#加入node程序并安装npm包
ADD ./ ./
RUN set -ex \
  && npm install -g cnpm --registry=https://registry.npm.taobao.org \
  && cnpm install egg-development-proxyworker \
  && cnpm install --production \
  && cd clientapp \
  && cnpm install \
  && NODE_ENV="production" cnpm run build:prod

CMD /bin/bash -c "npm run prod && while pidof node; do sleep 60; done"